all: data_stream_expander write_signal_handler packet_length_counter write_organizer data_storer ack_handler verifier data_reader rrrh roce_tx_interpreter udp_roce_rx_engine udp_roce_tx_engine roce_rx_interpreter fpga_malloc_free data_stream_compressor data_stream_expander udp_non_roce_rx_interpreter udp_non_roce_tx_interpreter 
packet_length_counter: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'packet_length_counter' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf packet_length_counter
	mkdir packet_length_counter
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

write_signal_handler: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'write_signal_handler' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf write_signal_handler
	mkdir write_signal_handler
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

write_organizer: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'write_organizer' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf write_organizer
	mkdir write_organizer
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

data_storer: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'data_storer' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf data_storer
	mkdir data_storer
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

verifier: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'verifier' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf verifier
	mkdir verifier
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

data_reader: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'data_reader' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf data_reader
	mkdir data_reader
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

rrrh: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'rrrh' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf rrrh
	mkdir rrrh
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

ack_handler: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'ack_handler' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf ack_handler
	mkdir ack_handler
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

roce_tx_interpreter: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'roce_tx_interpreter' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf roce_tx_interpreter
	mkdir roce_tx_interpreter
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

roce_rx_interpreter: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'roce_rx_interpreter' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf roce_rx_interpreter
	mkdir roce_rx_interpreter
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

udp_roce_rx_engine: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'udp_roce_rx_engine' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf udp_roce_rx_engine
	mkdir udp_roce_rx_engine
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

udp_roce_tx_engine: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'udp_roce_tx_engine' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf udp_roce_tx_engine
	mkdir udp_roce_tx_engine
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

fpga_malloc_free: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'fpga_malloc_free' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf fpga_malloc_free
	mkdir fpga_malloc_free
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

data_stream_compressor: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'data_stream_compressor' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf data_stream_compressor
	mkdir data_stream_compressor
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

data_stream_expander: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'data_stream_expander' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf data_stream_expander
	mkdir data_stream_expander
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

udp_non_roce_rx_interpreter: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'udp_non_roce_rx_interpreter' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf udp_non_roce_rx_interpreter
	mkdir udp_non_roce_rx_interpreter
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

udp_non_roce_tx_interpreter: ../../src/tcl/hls_builder.tcl ../../src/vhls/*
	rm -f Namefile.txt
	echo 'udp_non_roce_tx_interpreter' > Namefile.txt
	rm -f Speed_grade.txt
	echo '3.7' > Speed_grade.txt
	rm -rf udp_non_roce_tx_interpreter
	mkdir udp_non_roce_tx_interpreter
	vivado_hls ../../src/tcl/hls_builder.tcl
	rm -f vivado_hls.log
	rm -f Namefile.txt
	rm -f Speed_grade.txt

clean:
	rm -rf packet_length_counter udp_non_roce_tx_interpreter write_signal_handler write_organizer data_stream_compressor fpga_malloc_free roce_tx_interpreter udp_roce_tx_engine data_storer ack_handler verifier udp_non_roce_rx_interpreter data_reader rrrh Namefile.txt vivado_hls.log udp_roce_rx_engine roce_rx_interpreter data_stream_expander Namefile.txt Speed_grade.txt
